
title: Marc Berchtold - CV
url: 'http://www.hivenet.ch'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Marc Berchtold
tagline: Softwareentwickler/-architekt
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: marc.berchtold@hivenet.ch
phone: +41 (0)62 530 43 60
website: www.hivenet.ch #do not add http://
linkedin: alandoe
github: marcberchtold
twitter: '@HIVENETTEAM'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
